--http://www.onuryasar.com/blog/wp-content/uploads/2011/09/language.sql
INSERT INTO `preferredLanguage` (`idPreflanguage`, `description`, `code`) VALUES
(1, 'Alemannisch', 'al'),
(2, 'Ænglisc', 'an'),
(3, 'العربية', 'ar'),
(4, 'سنڌي', 'sd'),
(5, 'Azərbaycanca', 'az'),
(6, 'Български', 'bg'),
(7, 'Bahasa Banjar', 'bj'),
(8, 'বাংলা', 'bn'),
(9, 'Català', 'ca'),
(10, 'Česky', 'cs'),
(11, 'Словѣ́ньскъ', 'cu'),
(12, 'Deutsch', 'de'),
(13, 'Ελληνικά', 'el'),
(14, 'English', 'en'),
(15, 'Esperanto', 'eo'),
(16, 'Español', 'es'),
(17, 'فارسی', 'fa'),
(18, 'Suomi', 'fi'),
(19, 'Français', 'fr'),
(20, 'ગુજરાતી', 'gu'),
(21, 'עברית', 'he'),
(22, 'हिन्दी', 'hi'),
(23, 'Հայերեն', 'hy'),
(24, 'Bahasa Indonesia', 'id'),
(25, 'मराठी', 'mr'),
(26, 'Italiano', 'it'),
(27, '日本語', 'ja'),
(28, 'Basa Jawa', 'jv'),
(29, 'ქართული', 'ka'),
(30, '한국어', 'ko'),
(31, 'Latviešu', 'lv'),
(32, 'Lietuvių', 'lt'),
(33, 'Magyar', 'hu'),
(34, 'Bahasa Melayu', 'ms'),
(35, 'Македонски', 'mk'),
(36, 'مازِرونی', 'mz'),
(37, 'नेपाल भाषा', 'ne'),
(38, 'नेपाली', 'ne'),
(39, 'ਪੰਜਾਬੀ', 'pa'),
(40, 'Polski', 'pl'),
(41, 'پښتو', 'ps'),
(42, 'Português', 'pt'),
(43, 'Română', 'ro'),
(44, 'Русский', 'ru'),
(45, 'Svenska', 'sv'),
(46, 'தமிழ்', 'ta'),
(47, 'ไทย', 'th'),
(48, 'Türkçe', 'tr'),
(49, 'Українська', 'uk'),
(50, 'Tiếng Việt', 'vi'),
(51, 'Yorùbá', 'yo'),
(52, '中文', 'zh');